apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-test
  template:
    metadata:
      labels:
        app: ubuntu-test
    spec:
      containers:
        - name: ubuntu-test
          image: tifan12/ubuntu-test
          imagePullPolicy: IfNotPresent