apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test
spec:
  replicas: {{.Values.clients_replicas}}
  selector:
    matchLabels:
      app: {{.Values.name_client}}
  template:
    metadata:
      labels:
        app: {{.Values.name_client}}
    spec:
      containers:
        - name: {{.Values.name_client}}
          image: {{.Values.image_name_client}}
          imagePullPolicy: IfNotPresent