apiVersion: v1
kind: Service
metadata:
  name: flask-api-service-out
spec:
  selector:
    app: flask-api
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050
      protocol: TCP