## Tomado de https://faun.pub/run-your-flask-app-on-kubernetes-ff03854db842
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: {{.Values.api_replicas}}
  selector:
    matchLabels:
      app: {{.Values.name_flask_api}}
  template:
    metadata:
      labels:
        app: {{.Values.name_flask_api}}
    spec:
      containers:
        - name: {{.Values.name_flask_api}}
          image: {{.Values.image_name_api}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{.Values.flask_api_port}}
              protocol: TCP
          env:
            - name: PORT_API
              value: "5000"
            - name: IP_DNS
              value: '8.8.4.4'
            - name: PORT_DNS
              value: "53"