apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  selector:
    app: {{.Values.name_flask_api}}
  ports:
    - port: {{.Values.flask_api_port}}
      targetPort: {{.Values.flask_api_port}}
      protocol: TCP