version: '3.9'
services:
  router1:
    #build: ./routers/router1/
    image: tifan12/router1
    container_name: router1
    privileged: true
    ports: 
      - 80:80/tcp
      - 443:443/tcp
      - 8443:8443/tcp
    networks:
      bridge:
      lan1:
        ipv4_address: 10.0.0.10
  router2:
    #build: ./routers/router2/
    image: tifan12/router2
    container_name: router2
    privileged: true
    depends_on:
      - router1
    networks:
      lan1:
        ipv4_address: 10.0.0.2
      lan2:
        ipv4_address: 10.0.1.10
  dns:
    #build: ./dns/
    image: irsacfac/dns
    container_name: dns
    privileged: true
    ports: 
      - 53:53/tcp
      - 53:53/udp
    depends_on:
      - router1
      - router2
    networks:
      lan1: 
        ipv4_address: 10.0.0.3
  dhcp2:
    image: ary2000/dhcp2
    #build: ./dhcp/dhcp2/
    container_name: dhcp2
    #image: ary2000/dhcp2
    privileged: true
    depends_on:
      - dns
    networks:
      lan2:
        ipv4_address: 10.0.1.5
  dhcp1:
    image: ary2000/dhcp1
    #build: ./dhcp/dhcp1/
    container_name: dhcp1
    #image: ary2000/dhcp1
    privileged: true 
    depends_on:
      - dns
    networks:
      lan1:
        ipv4_address: 10.0.0.4 
  websrv1:
    image: mariofernandez20/websrv1
    container_name: httpd1
    depends_on:
      - dhcp1
      - dhcp2
    networks:
      lan1: 
        ipv4_address: 10.0.0.21
  websrv2:
    image: mariofernandez20/websrv2
    container_name: httpd2
    depends_on:
      - dhcp1
      - dhcp2
    networks:
      lan2:
        ipv4_address: 10.0.1.21
  webcache:
    image: ary2000/cache
    #build: ./cache/
    container_name: webcache
    #image: ary2000/cache
    privileged: true
    depends_on:
      - dhcp1
      - dhcp2
    cap_add:
      - NET_ADMIN
    networks:
      lan1:
        ipv4_address: 10.0.0.7
  cliente1:
    build: ./clients/client1
    container_name: cliente1
    privileged: true
    depends_on:
      - websrv1
      - websrv2
      - webcache
    networks:
      - lan1
  cliente2:
    build: ./clients/client2
    container_name: cliente2
    privileged: true
    depends_on:
      - websrv1
      - websrv2
      - webcache
    networks:
      - lan2
  vpn:
    #build: ./vpn
    image: tifan12/vpn
    container_name: vpn
    privileged: true
    depends_on:
      - dns
      - dhcp2
    networks:
      lan2:
        ipv4_address: 10.0.1.15
networks:
  lan1:
      driver: macvlan
      ipam:
          driver: default
          config:
              - subnet: 10.0.0.0/24
  lan2:
      driver: macvlan
      ipam:
          driver: default
          config:
              - subnet: 10.0.1.0/24
  bridge:
      ipam:
          driver: default