version: '3.9'
services:
  router1:
    build: ./routers/router1/
    container_name: router1
    privileged: true
    ports: 
      - 10000:80/tcp
    networks:
      bridge:
      lan1:
        ipv4_address: 10.0.0.10
  router2:
    build: ./routers/router2/
    container_name: router2
    privileged: true
    networks:
      lan1:
        ipv4_address: 10.0.0.2
      lan2:
        ipv4_address: 10.0.1.10
  dns:
    build: ./dns/
    container_name: dns
    privileged: true
    ports: 
      - 53/tcp
      - 53/udp
    networks:
      lan1: 
        ipv4_address: 10.0.0.3
  dhcp2:
    #image: ary2000/dhcp2
    build: ./dhcp/dhcp2/
    container_name: dhcp2
    privileged: true
    networks:
      lan2:
        ipv4_address: 10.0.1.5
  dhcp1:
    #image: ary2000/dhcp1
    build: ./dhcp/dhcp1/
    container_name: dhcp1
    privileged: true 
    networks:
      lan1:
        ipv4_address: 10.0.0.4 
  websrv1:
    image: mariofernandez20/websrv1
    container_name: httpd1
    networks:
      lan1: 
        ipv4_address: 10.0.0.21
  websrv2:
    image: mariofernandez20/websrv2
    container_name: httpd2
    networks:
      lan2:
        ipv4_address: 10.0.1.21
  webcache:
    build: ./cache/
    container_name: webcache
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - 3128/tcp
    networks:
      lan1:
        ipv4_address: 10.0.0.7
  cliente1:
    build: ./clients/client1
    container_name: cliente1
    privileged: true
    networks:
      lan1:
        ipv4_address: 10.0.0.11
  cliente2:
    build: ./clients/client2
    container_name: cliente2
    privileged: true
    networks:
      lan2:
        ipv4_address: 10.0.1.11
networks:
  lan1:
      driver: macvlan
      ipam:
          driver: default
          config:
              - subnet: 10.0.0.0/24
  lan2:
      driver: macvlan
      ipam:
          driver: default
          config:
              - subnet: 10.0.1.0/24
  bridge:
      ipam:
          driver: default