apiVersion: v1
kind: Service
metadata:
  name: dns-interceptor
spec:
  selector:
    app: {{.Values.name_dns_interceptor}}
  ports:
    - port: {{.Values.dns_interceptor_port}}
      targetPort: {{.Values.dns_interceptor_port}}
      protocol: UDP