## Tomado de https://faun.pub/run-your-flask-app-on-kubernetes-ff03854db842
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-interceptor-deployment
spec:
  replicas: {{.Values.dns_interceptor_replicas}}
  selector:
    matchLabels:
      app: {{.Values.name_dns_interceptor}}
  template:
    metadata:
      labels:
        app: {{.Values.name_dns_interceptor}}
    spec:
      containers:
        - name: {{.Values.name_dns_interceptor}}
          image: {{.Values.image_name_dns_interceptor}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{.Values.dns_interceptor_port}}
              protocol: UDP
          env:
            - name: ELASTIC_PASS
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-elastic-user
                  key: elastic
            - name: ECK_USER_PASS
              value: "elastic:$(ELASTIC_PASS)"
            - name: POST_INDEX
              value: "{ \"script\" : { \"source\": \"ctx._source.index += params.count\", \"params\" : { \"count\" : 1}}}"
            - name: POST_FIELD_1
              value: "{\"query\": {\"match\": {\"hostname\": {\"query\": \""
            - name: POST_FIELD_2
              value: "\"}}},\"fields\": [\"hostname\",\"index\",\"IP\",\"TTL\" ],\"_source\": false}"
            - name: URL_GET_ELASTIC
              value: "https://quickstart-es-default:9200/zones/_search/"
            - name: URL_UPDATE_ELASTIC
              value: "https://quickstart-es-default:9200/zones/_update/"
            - name: URL_POST_API
              value: "https://flask-api-service:5000/api/dns_resolver/"
            - name: DNS_INTERCEPTOR_PORT
              value: "53"