apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart-kb
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30601
      protocol: TCP