
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment_name}}
spec:
  replicas: {{.Values.replicas_number}}
  selector:
    matchLabels:
      app: {{.Values.deployment_name}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment_name}}
    spec:
      containers:
        - name: {{.Values.deployment_name}}
          image: {{.Values.image_dochub_name}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{.Values.port_number}}
              protocol: TCP