apiVersion: v1
kind: Service
metadata:
  name: tarea2-service
spec:
  selector:
    app: {{.Values.deployment_name}}
  type: NodePort
  ports:
    - name: http
      port: {{.Values.port_number}}
      targetPort: {{.Values.port_number}}
      nodePort: {{.Values.outside_port}}
      protocol: TCP
