version: '3'
services:
  api:
    build: ./api
    image: api-server
    ports:
      - "5000:5000"
    expose:
      - "5000"
  client:
    build: ./client
    image: ubuntu-test
  interceptor:
    build: ./interceptor
    image: dns-interceptor
    ports:
      - "53:53"
    expose:
      - "53"