openapi: 3.0.0
info:
  title: DNS API
  description: Esta es la documentación para el DNS API del proyecto 2 del curso de redes.
  version: 1.0.0
servers:
  - url: https://localhost:30050
    description: "Aquí se corre el API"
paths:
  /api/dns_resolver/:
    post:
      summary: Este se encarga de conseguir un DNS package, enviarselo a un DNS y devolvere la repsuesta al cliente que le dio el request original.
      requestBody:
        description: Paquete encriptado en base64
        required: true
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                code:
                  type: string
              example:   # Sample object
                code: aG9sYSBtdW5kbwo=

      responses:
        "response":
          description: Paquete encriptado de la respuesta ("aG9sYSBtdW5kbyByZXNwdWVzdGEK")