version: '3'
services:
  frontend:
    build: ./front-end
    ports:
      - "4001:3000"
  api:
    build: ./api
    ports:
      - "80:5000"
  game-controller:
    build: ./game-controler
    ports:
      - "6666"
